
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa,ba;h.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},q;for(q in h)h.hasOwnProperty(q)&&(ca[q]=h[q]);var fa="./this.program",ha=!1,v=!1,ia=!1,ja=!1;ha="object"===typeof window;v="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!ha&&!ia&&!v;var w="",ka,la,ma,na,oa;
if(ia)w=v?require("path").dirname(w)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",x),h.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=
typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ha||v)v?w=self.location.href:"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src),_scriptDir&&(w=_scriptDir),
0!==w.indexOf("blob:")?w=w.substr(0,w.lastIndexOf("/")+1):w="",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var pa=h.print||console.log.bind(console),A=h.printErr||console.warn.bind(console);for(q in ca)ca.hasOwnProperty(q)&&(h[q]=ca[q]);ca=null;h.thisProgram&&(fa=h.thisProgram);var qa;h.wasmBinary&&(qa=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!==typeof WebAssembly&&x("no native wasm support detected");var ra,sa=!1;function assert(a,b){a||x("Assertion failed: "+b)}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function B(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ua(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.charCodeAt(f);if(55296<=l&&57343>=l){var k=a.charCodeAt(++f);l=65536+((l&1023)<<10)|k&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function xa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ya[c];)++c;c<<=1;if(32<c-a&&wa)return wa.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function Aa(a){return 2*a.length}function Ba(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Ea,F,C,D,ya,E,G,Fa,Ga,Ha,Ia=[],Ja=[],Ka=[];function La(){var a=h.preRun.shift();Ia.unshift(a)}var H=0,Ma=null,Na=null;
h.preloadedImages={};h.preloadedAudios={};function x(a){if(h.onAbort)h.onAbort(a);A(a);sa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Oa(){return I.startsWith("data:application/octet-stream;base64,")}var I="blsjs.wasm";if(!Oa()){var Pa=I;I=h.locateFile?h.locateFile(Pa,w):w+Pa}
function Qa(){var a=I;try{if(a==I&&qa)return new Uint8Array(qa);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function Ra(){if(!qa&&(ha||v)){if("function"===typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Qa()});if(la)return new Promise(function(a,b){la(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Qa()})}
function Sa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.zb;"number"===typeof c?void 0===b.Ga?Ha.get(c)():Ha.get(c)(b.Ga):c(void 0===b.Ga?null:b.Ga)}}}function Ta(a){this.Y=a-16;this.sb=function(b){E[this.Y+8>>2]=b};this.pb=function(b){E[this.Y+0>>2]=b};this.qb=function(){E[this.Y+4>>2]=0};this.ob=function(){F[this.Y+12>>0]=0};this.rb=function(){F[this.Y+13>>0]=0};this.eb=function(b,c){this.sb(b);this.pb(c);this.qb();this.ob();this.rb()}}var Ua=0;
function Va(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Wa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Va(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Xa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ya(a){if("/"===a)return"/";a=Wa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Za(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){x("randomDevice")}}
function $a(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Va(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var ab=[];function bb(a,b){ab[a]={input:[],output:[],sa:b};cb(a,db)}
var db={open:function(a){var b=ab[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.sa.flush(a.tty)},flush:function(a){a.tty.sa.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.sa.Ra)throw new J(60);for(var e=0,f=0;f<d;f++){try{var l=a.tty.sa.Ra(a.tty)}catch(k){throw new J(29);}if(void 0===l&&0===e)throw new J(6);if(null===l||void 0===l)break;e++;b[c+f]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.sa.Ia)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.sa.Ia(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},fb={Ra:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.Wa?Buffer.Wa(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=eb(b,!0)}return a.input.shift()},Ia:function(a,b){null===b||10===b?(pa(B(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(pa(B(a.output,0)),a.output=[])}},gb={Ia:function(a,b){null===b||10===b?(A(B(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(A(B(a.output,0)),a.output=[])}},K={ia:null,la:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.ia||(K.ia={dir:{node:{ma:K.X.ma,ja:K.X.ja,lookup:K.X.lookup,Ba:K.X.Ba,rename:K.X.rename,unlink:K.X.unlink,rmdir:K.X.rmdir,readdir:K.X.readdir,symlink:K.X.symlink},stream:{va:K.$.va}},file:{node:{ma:K.X.ma,ja:K.X.ja},stream:{va:K.$.va,read:K.$.read,write:K.$.write,La:K.$.La,Sa:K.$.Sa,Ua:K.$.Ua}},link:{node:{ma:K.X.ma,ja:K.X.ja,readlink:K.X.readlink},stream:{}},Ma:{node:{ma:K.X.ma,ja:K.X.ja},stream:hb}});
c=ib(a,b,c,d);16384===(c.mode&61440)?(c.X=K.ia.dir.node,c.$=K.ia.dir.stream,c.W={}):32768===(c.mode&61440)?(c.X=K.ia.file.node,c.$=K.ia.file.stream,c.aa=0,c.W=null):40960===(c.mode&61440)?(c.X=K.ia.link.node,c.$=K.ia.link.stream):8192===(c.mode&61440)&&(c.X=K.ia.Ma.node,c.$=K.ia.Ma.stream);c.timestamp=Date.now();a&&(a.W[b]=c,a.timestamp=c.timestamp);return c},Ab:function(a){return a.W?a.W.subarray?a.W.subarray(0,a.aa):new Uint8Array(a.W):new Uint8Array(0)},Oa:function(a,b){var c=a.W?a.W.length:0;
c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.W,a.W=new Uint8Array(b),0<a.aa&&a.W.set(c.subarray(0,a.aa),0))},mb:function(a,b){if(a.aa!=b)if(0==b)a.W=null,a.aa=0;else{var c=a.W;a.W=new Uint8Array(b);c&&a.W.set(c.subarray(0,Math.min(b,a.aa)));a.aa=b}},X:{ma:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.aa:40960===(a.mode&61440)?
b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Xa=4096;b.blocks=Math.ceil(b.size/b.Xa);return b},ja:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.mb(a,b.size)},lookup:function(){throw jb[44];},Ba:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=kb(b,c)}catch(f){}if(d)for(var e in d.W)throw new J(55);
}delete a.parent.W[a.name];a.parent.timestamp=Date.now();a.name=c;b.W[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.W[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=kb(a,b),d;for(d in c.W)throw new J(55);delete a.W[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.W)a.W.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);
return a.link}},$:{read:function(a,b,c,d,e){var f=a.node.W;if(e>=a.node.aa)return 0;a=Math.min(a.node.aa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.W||a.W.subarray)){if(f)return a.W=b.subarray(c,c+d),a.aa=d;if(0===a.aa&&0===e)return a.W=b.slice(c,c+d),a.aa=d;if(e+d<=a.aa)return a.W.set(b.subarray(c,c+d),e),d}K.Oa(a,e+d);if(a.W.subarray&&b.subarray)a.W.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.W[e+f]=b[c+f];a.aa=Math.max(a.aa,e+d);return d},va:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.aa);if(0>b)throw new J(28);return b},La:function(a,b,c){K.Oa(a.node,b+c);a.node.aa=Math.max(a.node.aa,b+c)},Sa:function(a,b,c,d,e,f){if(0!==b)throw new J(28);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.W;if(f&2||a.buffer!==Ea){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=
65536*Math.ceil(c/65536);for(b=lb(f);c<f;)F[b+c++]=0;c=b;if(!c)throw new J(48);F.set(a,c)}else d=!1,c=a.byteOffset;return{Y:c,yb:d}},Ua:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.$.write(a,b,0,d,c,!1);return 0}}},mb=null,nb={},ob=[],pb=1,qb=null,rb={},J=null,jb={};
function L(a,b){a=$a("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Qa:!0,Ja:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ja)throw new J(32);a=Va(a.split("/").filter(function(l){return!!l}),!1);var e=mb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=kb(e,a[d]);c=Wa(c+"/"+a[d]);e.Ca&&(!f||f&&b.Qa)&&(e=e.Ca.root);if(!f||b.Pa)for(f=0;40960===(e.mode&61440);)if(e=sb(c),c=$a(Xa(c),e),e=L(c,{Ja:b.Ja}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function tb(a){for(var b;;){if(a===a.parent)return a=a.la.Ta,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function ub(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%qb.length}function kb(a,b){var c;if(c=a.X.lookup?0:2)throw new J(c,a);for(c=qb[ub(a.id,b)];c;c=c.hb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.X.lookup(a,b)}function ib(a,b,c,d){a=new vb(a,b,c,d);b=ub(a.parent.id,a.name);a.hb=qb[b];return qb[b]=a}
var wb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function xb(a,b){try{return kb(a,b),20}catch(c){}return 0}function yb(){var a=4096;for(var b=0;b<=a;b++)if(!ob[b])return b;throw new J(33);}function zb(a){Ab||(Ab=function(){},Ab.prototype={});var b=new Ab,c;for(c in a)b[c]=a[c];a=b;b=yb();a.fd=b;return ob[b]=a}var hb={open:function(a){a.$=nb[a.node.rdev].$;a.$.open&&a.$.open(a)},va:function(){throw new J(70);}};function cb(a,b){nb[a]={$:b}}
function Bb(a,b){var c="/"===b,d=!b;if(c&&mb)throw new J(10);if(!c&&!d){var e=L(b,{Qa:!1});b=e.path;e=e.node;if(e.Ca)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,Bb:{},Ta:b,gb:[]};a=a.la(b);a.la=b;b.root=a;c?mb=a:e&&(e.Ca=b,e.la&&e.la.gb.push(b))}function Cb(a,b,c){var d=L(a,{parent:!0}).node;a=Ya(a);if(!a||"."===a||".."===a)throw new J(28);var e=xb(d,a);if(e)throw new J(e);if(!d.X.Ba)throw new J(63);return d.X.Ba(d,a,b,c)}function M(a){return Cb(a,16895,0)}
function Db(a,b,c){"undefined"===typeof c&&(c=b,b=438);Cb(a,b|8192,c)}function Eb(a,b){if(!$a(a))throw new J(44);var c=L(b,{parent:!0}).node;if(!c)throw new J(44);b=Ya(b);var d=xb(c,b);if(d)throw new J(d);if(!c.X.symlink)throw new J(63);c.X.symlink(c,b,a)}function sb(a){a=L(a).node;if(!a)throw new J(44);if(!a.X.readlink)throw new J(28);return $a(tb(a.parent),a.X.readlink(a))}
function Fb(a,b,c){if(""===a)throw new J(44);if("string"===typeof b){var d=wb[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var e=a;else{a=Wa(a);try{e=L(a,{Pa:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new J(20);}else e=Cb(a,c,0),d=!0;if(!e)throw new J(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new J(54);if(!d){if(e)if(40960===(e.mode&61440))c=
32;else{if(c=16384===(e.mode&61440))c=["r","w","rw"][b&3],b&512&&(c+="w"),c="r"!==c||b&512;c=c?31:0}else c=44;if(c)throw new J(c);}if(b&512){c=e;c="string"===typeof c?L(c,{Pa:!0}).node:c;if(!c.X.ja)throw new J(63);if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);c.X.ja(c,{size:0,timestamp:Date.now()})}b&=-131713;e=zb({node:e,path:tb(e),flags:b,seekable:!0,position:0,$:e.$,Db:[],error:!1});e.$.open&&e.$.open(e);!h.logReadFiles||b&1||(Gb||(Gb={}),a in Gb||(Gb[a]=1,
A("FS.trackingDelegate error on read file: "+a)));try{rb.onOpenFile&&(c=0,1!==(b&2097155)&&(c|=1),0!==(b&2097155)&&(c|=2),rb.onOpenFile(a,c))}catch(f){A("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+f.message)}return e}function Hb(){J||(J=function(a,b){this.node=b;this.nb=function(c){this.ua=c};this.nb(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){jb[a]=new J(a);jb[a].stack="<generic error, no stack>"}))}var Ib;
function Jb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Kb(a,b,c){a=Wa("/dev/"+a);var d=Jb(!!b,!!c);Lb||(Lb=64);var e=Lb++<<8|0;cb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,l,k,p){for(var m=0,n=0;n<p;n++){try{var t=b()}catch(u){throw new J(29);}if(void 0===t&&0===m)throw new J(6);if(null===t||void 0===t)break;m++;l[k+n]=t}m&&(f.node.timestamp=Date.now());return m},write:function(f,l,k,p){for(var m=0;m<p;m++)try{c(l[k+m])}catch(n){throw new J(29);}p&&(f.node.timestamp=Date.now());return m}});
Db(a,d,e)}var Lb,Mb={},Ab,Gb,Nb=void 0;function Ob(a){a=ob[a];if(!a)throw new J(8);return a}function Pb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Qb=void 0;function N(a){for(var b="";C[a];)b+=Qb[C[a++]];return b}var O={},P={},Rb={};function Sb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Tb(a,b){a=Sb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ub(a){var b=Error,c=Tb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Q=void 0;function R(a){throw new Q(a);}var Vb=void 0;function Wb(a){throw new Vb(a);}function S(a,b,c){function d(k){k=c(k);k.length!==a.length&&Wb("Mismatched type converter count");for(var p=0;p<a.length;++p)T(a[p],k[p])}a.forEach(function(k){Rb[k]=b});var e=Array(b.length),f=[],l=0;b.forEach(function(k,p){P.hasOwnProperty(k)?e[p]=P[k]:(f.push(k),O.hasOwnProperty(k)||(O[k]=[]),O[k].push(function(){e[p]=P[k];++l;l===f.length&&d(e)}))});0===f.length&&d(e)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||R('type "'+d+'" must have a positive integer typeid pointer');if(P.hasOwnProperty(a)){if(c.cb)return;R("Cannot register type '"+d+"' twice")}P[a]=b;delete Rb[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(function(e){e()}))}function Xb(a){R(a.V.ba.Z.name+" instance already deleted")}var Yb=!1;function Zb(){}
function $b(a){--a.count.value;0===a.count.value&&(a.fa?a.ga.oa(a.fa):a.ba.Z.oa(a.Y))}function ac(a){if("undefined"===typeof FinalizationGroup)return ac=function(b){return b},a;Yb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Y?$b(c):console.warn("object already deleted: "+c.Y)});ac=function(b){Yb.register(b,b.V,b.V);return b};Zb=function(b){Yb.unregister(b.V)};return ac(a)}var bc=void 0,cc=[];
function dc(){for(;cc.length;){var a=cc.pop();a.V.qa=!1;a["delete"]()}}function U(){}var ec={};function fc(a,b,c){if(void 0===a[b].da){var d=a[b];a[b]=function(){a[b].da.hasOwnProperty(arguments.length)||R("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].da+")!");return a[b].da[arguments.length].apply(this,arguments)};a[b].da=[];a[b].da[d.pa]=d}}
function hc(a,b){h.hasOwnProperty(a)?(R("Cannot register public name '"+a+"' twice"),fc(h,a,a),h.hasOwnProperty(void 0)&&R("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),h[a].da[void 0]=b):h[a]=b}function ic(a,b,c,d,e,f,l,k){this.name=a;this.constructor=b;this.ra=c;this.oa=d;this.ha=e;this.$a=f;this.ya=l;this.Za=k;this.jb=[]}
function jc(a,b,c){for(;b!==c;)b.ya||R("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ya(a),b=b.ha;return a}function kc(a,b){if(null===b)return this.Ha&&R("null is not a valid "+this.name),0;b.V||R('Cannot pass "'+lc(b)+'" as a '+this.name);b.V.Y||R("Cannot pass deleted object as a pointer of type "+this.name);return jc(b.V.Y,b.V.ba.Z,this.Z)}
function mc(a,b){if(null===b){this.Ha&&R("null is not a valid "+this.name);if(this.Aa){var c=this.kb();null!==a&&a.push(this.oa,c);return c}return 0}b.V||R('Cannot pass "'+lc(b)+'" as a '+this.name);b.V.Y||R("Cannot pass deleted object as a pointer of type "+this.name);!this.za&&b.V.ba.za&&R("Cannot convert argument of type "+(b.V.ga?b.V.ga.name:b.V.ba.name)+" to parameter type "+this.name);c=jc(b.V.Y,b.V.ba.Z,this.Z);if(this.Aa)switch(void 0===b.V.fa&&R("Passing raw pointer to smart pointer is illegal"),
this.tb){case 0:b.V.ga===this?c=b.V.fa:R("Cannot convert argument of type "+(b.V.ga?b.V.ga.name:b.V.ba.name)+" to parameter type "+this.name);break;case 1:c=b.V.fa;break;case 2:if(b.V.ga===this)c=b.V.fa;else{var d=b.clone();c=this.lb(c,V(function(){d["delete"]()}));null!==a&&a.push(this.oa,c)}break;default:R("Unsupporting sharing policy")}return c}
function nc(a,b){if(null===b)return this.Ha&&R("null is not a valid "+this.name),0;b.V||R('Cannot pass "'+lc(b)+'" as a '+this.name);b.V.Y||R("Cannot pass deleted object as a pointer of type "+this.name);b.V.ba.za&&R("Cannot convert argument of type "+b.V.ba.name+" to parameter type "+this.name);return jc(b.V.Y,b.V.ba.Z,this.Z)}function oc(a){return this.fromWireType(G[a>>2])}function pc(a,b,c){if(b===c)return a;if(void 0===c.ha)return null;a=pc(a,b,c.ha);return null===a?null:c.Za(a)}var qc={};
function rc(a,b){for(void 0===b&&R("ptr should not be undefined");a.ha;)b=a.ya(b),a=a.ha;return qc[b]}function sc(a,b){b.ba&&b.Y||Wb("makeClassHandle requires ptr and ptrType");!!b.ga!==!!b.fa&&Wb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ac(Object.create(a,{V:{value:b}}))}
function W(a,b,c,d){this.name=a;this.Z=b;this.Ha=c;this.za=d;this.Aa=!1;this.oa=this.lb=this.kb=this.Va=this.tb=this.ib=void 0;void 0!==b.ha?this.toWireType=mc:(this.toWireType=d?kc:nc,this.ka=null)}function vc(a,b){h.hasOwnProperty(a)||Wb("Replacing nonexistant public symbol");h[a]=b;h[a].pa=void 0}
function wc(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=h["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=Ha.get(b).apply(null,c);return d}}function X(a,b){a=N(a);var c=a.includes("j")?wc(a,b):Ha.get(b);"function"!==typeof c&&R("unknown function pointer with signature "+a+": "+b);return c}var xc=void 0;function yc(a){a=zc(a);var b=N(a);Y(a);return b}
function Ac(a,b){function c(f){e[f]||P[f]||(Rb[f]?Rb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new xc(a+": "+d.map(yc).join([", "]));}function Bc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Tb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function Cc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Dc(a,b,c,d,e){var f=b.length;2>f&&R("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ka){k=!0;break}var p="void"!==b[0].name,m="",n="";for(c=0;c<f-2;++c)m+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Sb(a)+"("+m+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var t=k?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[R,d,e,Cc,b[0],b[1]];l&&(a+="var thisWired = classParam.toWireType("+t+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+t+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),d.push(b[c+2]);l&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(p?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=l?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].ka&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",m.push(f+"_dtor"),d.push(b[c].ka));p&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return Bc(m).apply(null,d)}function Ec(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}var Fc=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Gc(a){4<a&&0===--Z[a].Ka&&(Z[a]=void 0,Fc.push(a))}
function V(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Fc.length?Fc.pop():Z.length;Z[b]={Ka:1,value:a};return b}}function lc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Hc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Fa[c>>2])};case 3:return function(c){return this.fromWireType(Ga[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Ic(a,b,c){switch(b){case 0:return c?function(d){return F[d]}:function(d){return C[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return ya[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Jc(a){a||R("Cannot use deleted val. handle = "+a);return Z[a].value}function Kc(a,b){var c=P[a];void 0===c&&R(b+" has unknown type "+yc(a));return c}var Lc={};
function Mc(a){var b=Lc[a];return void 0===b?N(a):b}var Nc=[];function Oc(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Pc(a){var b=Nc.length;Nc.push(a);return b}function Qc(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Kc(E[(b>>2)+d],"parameter "+d);return c}var Rc={},Sc={};
function Tc(){if(!Uc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Sc)a[b]=Sc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Uc=c}return Uc}var Uc;function Vc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Wc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Xc=[31,29,31,30,31,30,31,31,30,31,30,31],Yc=[31,28,31,30,31,30,31,31,30,31,30,31];function Zc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Vc(a.getFullYear())?Xc:Yc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function $c(a,b,c,d){function e(g,r,y){for(g="number"===typeof g?g.toString():g||"";g.length<r;)g=y[0]+g;return g}function f(g,r){return e(g,r,"0")}function l(g,r){function y(da){return 0>da?-1:0<da?1:0}var z;0===(z=y(g.getFullYear()-r.getFullYear()))&&0===(z=y(g.getMonth()-r.getMonth()))&&(z=y(g.getDate()-r.getDate()));return z}function k(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function p(g){g=Zc(new Date(g.ea+1900,0,1),g.Fa);var r=new Date(g.getFullYear()+1,0,4),y=k(new Date(g.getFullYear(),0,4));r=k(r);return 0>=l(y,g)?0>=l(r,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var m=E[d+40>>2];d={wb:E[d>>2],vb:E[d+4>>2],Da:E[d+8>>2],xa:E[d+12>>2],ta:E[d+16>>2],ea:E[d+20>>2],Ea:E[d+24>>2],Fa:E[d+28>>2],Cb:E[d+32>>2],ub:E[d+
36>>2],xb:m?m?B(C,m,void 0):"":""};c=c?B(C,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in m)c=c.replace(new RegExp(n,"g"),m[n]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");m={"%a":function(g){return t[g.Ea].substring(0,3)},"%A":function(g){return t[g.Ea]},"%b":function(g){return u[g.ta].substring(0,3)},"%B":function(g){return u[g.ta]},"%C":function(g){return f((g.ea+1900)/100|0,2)},"%d":function(g){return f(g.xa,2)},"%e":function(g){return e(g.xa,2," ")},"%g":function(g){return p(g).toString().substring(2)},"%G":function(g){return p(g)},"%H":function(g){return f(g.Da,
2)},"%I":function(g){g=g.Da;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":function(g){return f(g.xa+Wc(Vc(g.ea+1900)?Xc:Yc,g.ta-1),3)},"%m":function(g){return f(g.ta+1,2)},"%M":function(g){return f(g.vb,2)},"%n":function(){return"\n"},"%p":function(g){return 0<=g.Da&&12>g.Da?"AM":"PM"},"%S":function(g){return f(g.wb,2)},"%t":function(){return"\t"},"%u":function(g){return g.Ea||7},"%U":function(g){var r=new Date(g.ea+1900,0,1),y=0===r.getDay()?r:Zc(r,7-r.getDay());g=new Date(g.ea+1900,g.ta,g.xa);return 0>
l(y,g)?f(Math.ceil((31-y.getDate()+(Wc(Vc(g.getFullYear())?Xc:Yc,g.getMonth()-1)-31)+g.getDate())/7),2):0===l(y,r)?"01":"00"},"%V":function(g){var r=new Date(g.ea+1901,0,4),y=k(new Date(g.ea+1900,0,4));r=k(r);var z=Zc(new Date(g.ea+1900,0,1),g.Fa);return 0>l(z,y)?"53":0>=l(r,z)?"01":f(Math.ceil((y.getFullYear()<g.ea+1900?g.Fa+32-y.getDate():g.Fa+1-y.getDate())/7),2)},"%w":function(g){return g.Ea},"%W":function(g){var r=new Date(g.ea,0,1),y=1===r.getDay()?r:Zc(r,0===r.getDay()?1:7-r.getDay()+1);g=
new Date(g.ea+1900,g.ta,g.xa);return 0>l(y,g)?f(Math.ceil((31-y.getDate()+(Wc(Vc(g.getFullYear())?Xc:Yc,g.getMonth()-1)-31)+g.getDate())/7),2):0===l(y,r)?"01":"00"},"%y":function(g){return(g.ea+1900).toString().substring(2)},"%Y":function(g){return g.ea+1900},"%z":function(g){g=g.ub;var r=0<=g;g=Math.abs(g)/60;return(r?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":function(g){return g.xb},"%%":function(){return"%"}};for(n in m)c.includes(n)&&(c=c.replace(new RegExp(n,"g"),m[n](d)));n=eb(c,
!1);if(n.length>b)return 0;F.set(n,a);return n.length-1}function vb(a,b,c,d){a||(a=this);this.parent=a;this.la=a.la;this.Ca=null;this.id=pb++;this.name=b;this.mode=c;this.X={};this.$={};this.rdev=d}Object.defineProperties(vb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Hb();qb=Array(4096);Bb(K,"/");M("/tmp");M("/home");M("/home/web_user");
(function(){M("/dev");cb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Db("/dev/null",259);bb(1280,fb);bb(1536,gb);Db("/dev/tty",1280);Db("/dev/tty1",1536);var a=Za();Kb("random",a);Kb("urandom",a);M("/dev/shm");M("/dev/shm/tmp")})();
(function(){M("/proc");var a=M("/proc/self");M("/proc/self/fd");Bb({la:function(){var b=ib(a,"fd",16895,73);b.X={lookup:function(c,d){var e=ob[+d];if(!e)throw new J(8);c={parent:null,la:{Ta:"fake"},X:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var ad=Array(256),bd=0;256>bd;++bd)ad[bd]=String.fromCharCode(bd);Qb=ad;Q=h.BindingError=Ub("BindingError");Vb=h.InternalError=Ub("InternalError");
U.prototype.isAliasOf=function(a){if(!(this instanceof U&&a instanceof U))return!1;var b=this.V.ba.Z,c=this.V.Y,d=a.V.ba.Z;for(a=a.V.Y;b.ha;)c=b.ya(c),b=b.ha;for(;d.ha;)a=d.ya(a),d=d.ha;return b===d&&c===a};U.prototype.clone=function(){this.V.Y||Xb(this);if(this.V.wa)return this.V.count.value+=1,this;var a=ac,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.V;a=a(c.call(b,d,{V:{value:{count:e.count,qa:e.qa,wa:e.wa,Y:e.Y,ba:e.ba,fa:e.fa,ga:e.ga}}}));a.V.count.value+=1;a.V.qa=!1;return a};
U.prototype["delete"]=function(){this.V.Y||Xb(this);this.V.qa&&!this.V.wa&&R("Object already scheduled for deletion");Zb(this);$b(this.V);this.V.wa||(this.V.fa=void 0,this.V.Y=void 0)};U.prototype.isDeleted=function(){return!this.V.Y};U.prototype.deleteLater=function(){this.V.Y||Xb(this);this.V.qa&&!this.V.wa&&R("Object already scheduled for deletion");cc.push(this);1===cc.length&&bc&&bc(dc);this.V.qa=!0;return this};W.prototype.ab=function(a){this.Va&&(a=this.Va(a));return a};
W.prototype.Na=function(a){this.oa&&this.oa(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=oc;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.Aa?sc(this.Z.ra,{ba:this.ib,Y:c,ga:this,fa:a}):sc(this.Z.ra,{ba:this,Y:a})}var c=this.ab(a);if(!c)return this.Na(a),null;var d=rc(this.Z,c);if(void 0!==d){if(0===d.V.count.value)return d.V.Y=c,d.V.fa=a,d.clone();d=d.clone();this.Na(a);return d}d=this.Z.$a(c);d=ec[d];if(!d)return b.call(this);d=this.za?d.Ya:d.pointerType;var e=pc(c,this.Z,d.Z);return null===e?b.call(this):this.Aa?sc(d.Z.ra,{ba:d,Y:e,ga:this,fa:a}):sc(d.Z.ra,{ba:d,Y:e})};
h.getInheritedInstanceCount=function(){return Object.keys(qc).length};h.getLiveInheritedInstances=function(){var a=[],b;for(b in qc)qc.hasOwnProperty(b)&&a.push(qc[b]);return a};h.flushPendingDeletes=dc;h.setDelayFunction=function(a){bc=a;cc.length&&bc&&bc(dc)};xc=h.UnboundTypeError=Ub("UnboundTypeError");h.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};h.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
function eb(a,b){var c=Array(va(a)+1);a=ua(a,c,0,c.length);b&&(c.length=a);return c}
var cd={d:function(a){return lb(a+16)+16},e:function(a,b,c){(new Ta(a)).eb(b,c);Ua++;throw a;},D:function(a,b,c){Nb=c;try{var d=a?B(C,a,void 0):"";if(c){Nb+=4;var e=E[Nb-4>>2]}else e=0;return Fb(d,b,e).fd}catch(f){return"undefined"!==typeof Mb&&f instanceof J||x(f),-f.ua}},w:function(){},F:function(a,b,c,d,e){var f=Pb(c);b=N(b);T(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=F;else if(2===c)k=D;
else if(4===c)k=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>f])},ka:null})},l:function(a,b,c,d,e,f,l,k,p,m,n,t,u){n=N(n);f=X(e,f);k&&(k=X(l,k));m&&(m=X(p,m));u=X(t,u);var g=Sb(n);hc(g,function(){Ac("Cannot construct "+n+" due to unbound types",[d])});S([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var y=r.Z;var z=y.ra}else z=U.prototype;r=Tb(g,function(){if(Object.getPrototypeOf(this)!==da)throw new Q("Use 'new' to construct "+n);if(void 0===ea.na)throw new Q(n+
" has no accessible constructor");var tc=ea.na[arguments.length];if(void 0===tc)throw new Q("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(ea.na).toString()+") parameters instead!");return tc.apply(this,arguments)});var da=Object.create(z,{constructor:{value:r}});r.prototype=da;var ea=new ic(n,r,da,u,y,f,k,m);y=new W(n,ea,!0,!1);z=new W(n+"*",ea,!1,!1);var uc=new W(n+" const*",ea,!1,!0);ec[a]={pointerType:z,Ya:uc};vc(g,r);return[y,
z,uc]})},b:function(a,b,c,d,e,f,l){var k=Ec(c,d);b=N(b);f=X(e,f);S([],[a],function(p){function m(){Ac("Cannot call "+n+" due to unbound types",k)}p=p[0];var n=p.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var t=p.Z.constructor;void 0===t[b]?(m.pa=c-1,t[b]=m):(fc(t,b,n),t[b].da[c-1]=m);S([],k,function(u){u=[u[0],null].concat(u.slice(1));u=Dc(n,u,null,f,l);void 0===t[b].da?(u.pa=c-1,t[b]=u):t[b].da[c-1]=u;return[]});return[]})},p:function(a,b,c,d,e,f,l,k){b=N(b);f=X(e,f);S([],[a],function(p){p=
p[0];var m=p.name+"."+b,n={get:function(){Ac("Cannot access "+m+" due to unbound types",[c])},enumerable:!0,configurable:!0};k?n.set=function(){Ac("Cannot access "+m+" due to unbound types",[c])}:n.set=function(){R(m+" is a read-only property")};Object.defineProperty(p.Z.constructor,b,n);S([],[c],function(t){t=t[0];var u={get:function(){return t.fromWireType(f(d))},enumerable:!0};k&&(k=X(l,k),u.set=function(g){var r=[];k(d,t.toWireType(r,g));Cc(r)});Object.defineProperty(p.Z.constructor,b,u);return[]});
return[]})},r:function(a,b,c,d,e,f){assert(0<b);var l=Ec(b,c);e=X(d,e);var k=[f],p=[];S([],[a],function(m){m=m[0];var n="constructor "+m.name;void 0===m.Z.na&&(m.Z.na=[]);if(void 0!==m.Z.na[b-1])throw new Q("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.Z.na[b-1]=function(){Ac("Cannot construct "+m.name+" due to unbound types",l)};S([],
l,function(t){m.Z.na[b-1]=function(){arguments.length!==b-1&&R(n+" called with "+arguments.length+" arguments, expected "+(b-1));p.length=0;k.length=b;for(var u=1;u<b;++u)k[u]=t[u].toWireType(p,arguments[u-1]);u=e.apply(null,k);Cc(p);return t[0].fromWireType(u)};return[]});return[]})},f:function(a,b,c,d,e,f,l,k){var p=Ec(c,d);b=N(b);f=X(e,f);S([],[a],function(m){function n(){Ac("Cannot call "+t+" due to unbound types",p)}m=m[0];var t=m.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&
m.Z.jb.push(b);var u=m.Z.ra,g=u[b];void 0===g||void 0===g.da&&g.className!==m.name&&g.pa===c-2?(n.pa=c-2,n.className=m.name,u[b]=n):(fc(u,b,t),u[b].da[c-2]=n);S([],p,function(r){r=Dc(t,r,m,f,l);void 0===u[b].da?(r.pa=c-2,u[b]=r):u[b].da[c-2]=r;return[]});return[]})},E:function(a,b){b=N(b);T(a,{name:b,fromWireType:function(c){var d=Z[c].value;Gc(c);return d},toWireType:function(c,d){return V(d)},argPackAdvance:8,readValueFromPointer:oc,ka:null})},s:function(a,b,c){c=Pb(c);b=N(b);T(a,{name:b,fromWireType:function(d){return d},
toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+lc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Hc(b,c),ka:null})},k:function(a,b,c,d,e){function f(m){return m}b=N(b);-1===e&&(e=4294967295);var l=Pb(c);if(0===d){var k=32-8*c;f=function(m){return m<<k>>>k}}var p=b.includes("unsigned");T(a,{name:b,fromWireType:f,toWireType:function(m,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+
lc(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+lc(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return p?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Ic(b,l,0!==d),ka:null})},g:function(a,b,c){function d(f){f>>=2;var l=G;return new e(Ea,l[f+1],l[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=N(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,
readValueFromPointer:d},{cb:!0})},t:function(a,b){b=N(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var e=G[d>>2];if(c)for(var f=d+4,l=0;l<=e;++l){var k=d+4+l;if(l==e||0==C[k]){f=f?B(C,f,k-f):"";if(void 0===p)var p=f;else p+=String.fromCharCode(0),p+=f;f=k+1}}else{p=Array(e);for(l=0;l<e;++l)p[l]=String.fromCharCode(C[d+4+l]);p=p.join("")}Y(d);return p},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof
Uint8ClampedArray||e instanceof Int8Array||R("Cannot pass non-string to std::string");var l=(c&&f?function(){return va(e)}:function(){return e.length})(),k=lb(4+l+1);G[k>>2]=l;if(c&&f)ua(e,C,k+4,l+1);else if(f)for(f=0;f<l;++f){var p=e.charCodeAt(f);255<p&&(Y(k),R("String has UTF-16 code units that do not fit in 8 bits"));C[k+4+f]=p}else for(f=0;f<l;++f)C[k+4+f]=e[f];null!==d&&d.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:oc,ka:function(d){Y(d)}})},o:function(a,b,c){c=N(c);if(2===b){var d=
xa;var e=za;var f=Aa;var l=function(){return ya};var k=1}else 4===b&&(d=Ba,e=Ca,f=Da,l=function(){return G},k=2);T(a,{name:c,fromWireType:function(p){for(var m=G[p>>2],n=l(),t,u=p+4,g=0;g<=m;++g){var r=p+4+g*b;if(g==m||0==n[r>>k])u=d(u,r-u),void 0===t?t=u:(t+=String.fromCharCode(0),t+=u),u=r+b}Y(p);return t},toWireType:function(p,m){"string"!==typeof m&&R("Cannot pass non-string to C++ string type "+c);var n=f(m),t=lb(4+n+b);G[t>>2]=n>>k;e(m,t+4,n+b);null!==p&&p.push(Y,t);return t},argPackAdvance:8,
readValueFromPointer:oc,ka:function(p){Y(p)}})},G:function(a,b){b=N(b);T(a,{fb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},i:function(a,b,c){a=Jc(a);b=Kc(b,"emval::as");var d=[],e=V(d);E[c>>2]=e;return b.toWireType(d,a)},H:function(a,b,c,d,e){a=Nc[a];b=Jc(b);c=Mc(c);var f=[];E[d>>2]=V(f);return a(b,c,f,e)},I:function(a,b,c,d){a=Nc[a];b=Jc(b);c=Mc(c);a(b,c,null,d)},a:Gc,v:function(a){if(0===a)return V(Oc());a=Mc(a);return V(Oc()[a])},u:function(a,b){b=Qc(a,b);for(var c=
b[0],d=c.name+"_$"+b.slice(1).map(function(m){return m.name}).join("_")+"$",e=["retType"],f=[c],l="",k=0;k<a-1;++k)l+=(0!==k?", ":"")+"arg"+k,e.push("argType"+k),f.push(b[1+k]);d="return function "+Sb("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var p=0;for(k=0;k<a-1;++k)d+="    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(p?"+"+p:"")+");\n",p+=b[k+1].argPackAdvance;d+="    var rv = handle[name]("+l+");\n";for(k=0;k<a-1;++k)b[k+1].deleteObject&&(d+="    argType"+k+".deleteObject(arg"+
k+");\n");c.fb||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Bc(e).apply(null,f);return Pc(a)},j:function(a,b){a=Jc(a);b=Jc(b);return V(a[b])},c:function(a){4<a&&(Z[a].Ka+=1)},J:function(a,b,c,d){a=Jc(a);var e=Rc[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var l="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)l+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+
f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",l+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Kc,h,V);Rc[b]=e}return e(a,c,d)},m:function(a){return V(Mc(a))},h:function(a){Cc(Z[a].value);Gc(a)},n:function(a,b){a=Kc(a,"_emval_take_value");a=a.readValueFromPointer(b);return V(a)},q:function(){x()},x:function(){x("OOM")},z:function(a,b){try{var c=
0;Tc().forEach(function(d,e){var f=b+c;e=E[a+4*e>>2]=f;for(f=0;f<d.length;++f)F[e++>>0]=d.charCodeAt(f);F[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Mb&&d instanceof J||x(d),d.ua}},A:function(a,b){try{var c=Tc();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0}catch(e){return"undefined"!==typeof Mb&&e instanceof J||x(e),e.ua}},B:function(a){try{var b=Ob(a);if(null===b.fd)throw new J(8);b.bb&&(b.bb=null);try{b.$.close&&b.$.close(b)}catch(c){throw c;
}finally{ob[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof Mb&&c instanceof J||x(c),c.ua}},C:function(a,b,c,d){try{a:{for(var e=Ob(a),f=a=0;f<c;f++){var l=E[b+(8*f+4)>>2],k=e,p=E[b+8*f>>2],m=l,n=void 0,t=F;if(0>m||0>n)throw new J(28);if(null===k.fd)throw new J(8);if(1===(k.flags&2097155))throw new J(8);if(16384===(k.node.mode&61440))throw new J(31);if(!k.$.read)throw new J(28);var u="undefined"!==typeof n;if(!u)n=k.position;else if(!k.seekable)throw new J(70);var g=k.$.read(k,t,
p,m,n);u||(k.position+=g);var r=g;if(0>r){var y=-1;break a}a+=r;if(r<l)break}y=a}E[d>>2]=y;return 0}catch(z){return"undefined"!==typeof Mb&&z instanceof J||x(z),z.ua}},y:function(a,b,c,d){return $c(a,b,c,d)}};
(function(){function a(e){h.asm=e.exports;ra=h.asm.K;Ea=e=ra.buffer;h.HEAP8=F=new Int8Array(e);h.HEAP16=D=new Int16Array(e);h.HEAP32=E=new Int32Array(e);h.HEAPU8=C=new Uint8Array(e);h.HEAPU16=ya=new Uint16Array(e);h.HEAPU32=G=new Uint32Array(e);h.HEAPF32=Fa=new Float32Array(e);h.HEAPF64=Ga=new Float64Array(e);Ha=h.asm.N;Ja.unshift(h.asm.L);H--;h.monitorRunDependencies&&h.monitorRunDependencies(H);0==H&&(null!==Ma&&(clearInterval(Ma),Ma=null),Na&&(e=Na,Na=null,e()))}function b(e){a(e.instance)}function c(e){return Ra().then(function(f){return WebAssembly.instantiate(f,
d)}).then(e,function(f){A("failed to asynchronously prepare wasm: "+f);x(f)})}var d={a:cd};H++;h.monitorRunDependencies&&h.monitorRunDependencies(H);if(h.instantiateWasm)try{return h.instantiateWasm(d,a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return qa||"function"!==typeof WebAssembly.instantiateStreaming||Oa()||I.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){A("wasm streaming compile failed: "+f);A("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.L).apply(null,arguments)};var lb=h._malloc=function(){return(lb=h._malloc=h.asm.M).apply(null,arguments)},Y=h._free=function(){return(Y=h._free=h.asm.O).apply(null,arguments)},zc=h.___getTypeName=function(){return(zc=h.___getTypeName=h.asm.P).apply(null,arguments)};
h.___embind_register_native_and_builtin_types=function(){return(h.___embind_register_native_and_builtin_types=h.asm.Q).apply(null,arguments)};h.dynCall_iiiiij=function(){return(h.dynCall_iiiiij=h.asm.R).apply(null,arguments)};h.dynCall_iiiiijj=function(){return(h.dynCall_iiiiijj=h.asm.S).apply(null,arguments)};h.dynCall_iiiiiijj=function(){return(h.dynCall_iiiiiijj=h.asm.T).apply(null,arguments)};h.dynCall_viijii=function(){return(h.dynCall_viijii=h.asm.U).apply(null,arguments)};var dd;
Na=function ed(){dd||fd();dd||(Na=ed)};
function fd(){function a(){if(!dd&&(dd=!0,h.calledRun=!0,!sa)){h.noFSInit||Ib||(Ib=!0,Hb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Kb("stdin",h.stdin):Eb("/dev/tty","/dev/stdin"),h.stdout?Kb("stdout",null,h.stdout):Eb("/dev/tty","/dev/stdout"),h.stderr?Kb("stderr",null,h.stderr):Eb("/dev/tty1","/dev/stderr"),Fb("/dev/stdin",0),Fb("/dev/stdout",1),Fb("/dev/stderr",1));Sa(Ja);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Ka.unshift(b)}Sa(Ka)}}if(!(0<H)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)La();Sa(Ia);0<H||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}h.run=fd;if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();fd();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
