
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},n;for(n in g)g.hasOwnProperty(n)&&(ca[n]=g[n]);var ea=!1,t=!1,fa=!1,ha=!1;ea="object"===typeof window;t="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!t;var u="",ia,ja,ka,la,ma;
if(fa)u=t?require("path").dirname(u)+"/":__dirname+"/",ia=function(a,b){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);return la.readFileSync(a,b?null:"utf8")},ka=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",x),g.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=
typeof read&&(ia=function(a){return read(a)}),ka=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||t)t?u=self.location.href:"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),
0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var na=g.print||console.log.bind(console),y=g.printErr||console.warn.bind(console);for(n in ca)ca.hasOwnProperty(n)&&(g[n]=ca[n]);ca=null;var oa;g.wasmBinary&&(oa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&x("no native wasm support detected");var pa,qa=!1;function assert(a,b){a||x("Assertion failed: "+b)}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function z(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function sa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var h=a.charCodeAt(++f);k=65536+((k&1023)<<10)|h&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ua="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function va(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&wa[c];)++c;c<<=1;if(32<c-a&&ua)return ua.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function xa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d}function ya(a){return 2*a.length}function za(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Aa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}function Ba(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var Ca,D,A,B,wa,C,E,Da,Ea,Fa,Ga=[],Ha=[],Ia=[];function Ja(){var a=g.preRun.shift();Ga.unshift(a)}var F=0,Ka=null,La=null;
g.preloadedImages={};g.preloadedAudios={};function x(a){if(g.onAbort)g.onAbort(a);y(a);qa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ma(){return G.startsWith("data:application/octet-stream;base64,")}var G="blsjs.wasm";if(!Ma()){var Na=G;G=g.locateFile?g.locateFile(Na,u):u+Na}
function Oa(){var a=G;try{if(a==G&&oa)return new Uint8Array(oa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}
function Pa(){if(!oa&&(ea||t)){if("function"===typeof fetch&&!G.startsWith("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return Oa()});if(ja)return new Promise(function(a,b){ja(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Oa()})}
function Qa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.jb;"number"===typeof c?void 0===b.ta?Fa.get(c)():Fa.get(c)(b.ta):c(void 0===b.ta?null:b.ta)}}}function Ra(a){this.S=a-16;this.gb=function(b){C[this.S+8>>2]=b};this.cb=function(b){C[this.S+0>>2]=b};this.eb=function(){C[this.S+4>>2]=0};this.bb=function(){D[this.S+12>>0]=0};this.fb=function(){D[this.S+13>>0]=0};this.Sa=function(b,c){this.gb(b);this.cb(c);this.eb();this.bb();this.fb()}}var Sa=0;
function Ta(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Ua(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ta(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Va(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Wa(a){if("/"===a)return"/";a=Ua(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Xa(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(fa)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){x("randomDevice")}}
function Ya(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ta(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Za=[];function $a(a,b){Za[a]={input:[],output:[],la:b};ab(a,bb)}
var bb={open:function(a){var b=Za[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.la.flush(a.tty)},flush:function(a){a.tty.la.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.la.Fa)throw new H(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.la.Fa(a.tty)}catch(h){throw new H(29);}if(void 0===k&&0===e)throw new H(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.la.wa)throw new H(60);
try{for(var e=0;e<d;e++)a.tty.la.wa(a.tty,b[c+e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},cb={Fa:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.Ka?Buffer.Ka(256):new Buffer(256),d=0;try{d=la.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(ta(b)+1);b=sa(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},wa:function(a,b){null===b||10===b?(na(z(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(z(a.output,0)),a.output=[])}},db={wa:function(a,b){null===b||10===b?(y(z(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(y(z(a.output,0)),a.output=[])}},I={aa:null,
ea:function(){return I.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.aa||(I.aa={dir:{node:{fa:I.R.fa,ba:I.R.ba,lookup:I.R.lookup,ra:I.R.ra,rename:I.R.rename,unlink:I.R.unlink,rmdir:I.R.rmdir,readdir:I.R.readdir,symlink:I.R.symlink},stream:{ma:I.U.ma}},file:{node:{fa:I.R.fa,ba:I.R.ba},stream:{ma:I.U.ma,read:I.U.read,write:I.U.write,za:I.U.za,Ga:I.U.Ga,Ia:I.U.Ia}},link:{node:{fa:I.R.fa,ba:I.R.ba,readlink:I.R.readlink},stream:{}},
Aa:{node:{fa:I.R.fa,ba:I.R.ba},stream:eb}});c=fb(a,b,c,d);16384===(c.mode&61440)?(c.R=I.aa.dir.node,c.U=I.aa.dir.stream,c.P={}):32768===(c.mode&61440)?(c.R=I.aa.file.node,c.U=I.aa.file.stream,c.V=0,c.P=null):40960===(c.mode&61440)?(c.R=I.aa.link.node,c.U=I.aa.link.stream):8192===(c.mode&61440)&&(c.R=I.aa.Aa.node,c.U=I.aa.Aa.stream);c.timestamp=Date.now();a&&(a.P[b]=c,a.timestamp=c.timestamp);return c},kb:function(a){return a.P?a.P.subarray?a.P.subarray(0,a.V):new Uint8Array(a.P):new Uint8Array(0)},
Ca:function(a,b){var c=a.P?a.P.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.P,a.P=new Uint8Array(b),0<a.V&&a.P.set(c.subarray(0,a.V),0))},$a:function(a,b){if(a.V!=b)if(0==b)a.P=null,a.V=0;else{var c=a.P;a.P=new Uint8Array(b);c&&a.P.set(c.subarray(0,Math.min(b,a.V)));a.V=b}},R:{fa:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?
b.size=a.V:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.La=4096;b.blocks=Math.ceil(b.size/b.La);return b},ba:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&I.$a(a,b.size)},lookup:function(){throw gb[44];},ra:function(a,b,c,d){return I.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=hb(b,c)}catch(f){}if(d)for(var e in d.P)throw new H(55);
}delete a.parent.P[a.name];a.parent.timestamp=Date.now();a.name=c;b.P[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.P[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=hb(a,b),d;for(d in c.P)throw new H(55);delete a.P[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.P)a.P.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new H(28);
return a.link}},U:{read:function(a,b,c,d,e){var f=a.node.P;if(e>=a.node.V)return 0;a=Math.min(a.node.V-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.P||a.P.subarray)){if(f)return a.P=b.subarray(c,c+d),a.V=d;if(0===a.V&&0===e)return a.P=b.slice(c,c+d),a.V=d;if(e+d<=a.V)return a.P.set(b.subarray(c,c+d),e),d}I.Ca(a,e+d);if(a.P.subarray&&b.subarray)a.P.set(b.subarray(c,
c+d),e);else for(f=0;f<d;f++)a.P[e+f]=b[c+f];a.V=Math.max(a.V,e+d);return d},ma:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.V);if(0>b)throw new H(28);return b},za:function(a,b,c){I.Ca(a.node,b+c);a.node.V=Math.max(a.node.V,b+c)},Ga:function(a,b,c,d,e,f){if(0!==b)throw new H(28);if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.P;if(f&2||a.buffer!==Ca){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=65536*
Math.ceil(c/65536);for(b=ib(f);c<f;)D[b+c++]=0;c=b;if(!c)throw new H(48);D.set(a,c)}else d=!1,c=a.byteOffset;return{S:c,ib:d}},Ia:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);if(e&2)return 0;I.U.write(a,b,0,d,c,!1);return 0}}},jb=null,kb={},lb=[],mb=1,nb=null,pb={},H=null,gb={};
function J(a,b){a=Ya("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ea:!0,xa:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.xa)throw new H(32);a=Ta(a.split("/").filter(function(k){return!!k}),!1);var e=jb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=hb(e,a[d]);c=Ua(c+"/"+a[d]);e.sa&&(!f||f&&b.Ea)&&(e=e.sa.root);if(!f||b.Da)for(f=0;40960===(e.mode&61440);)if(e=qb(c),c=Ya(Va(c),e),e=J(c,{xa:b.xa}).node,40<f++)throw new H(32);}return{path:c,node:e}}
function rb(a){for(var b;;){if(a===a.parent)return a=a.ea.Ha,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function sb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%nb.length}function hb(a,b){var c;if(c=a.R.lookup?0:2)throw new H(c,a);for(c=nb[sb(a.id,b)];c;c=c.Va){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.R.lookup(a,b)}function fb(a,b,c,d){a=new tb(a,b,c,d);b=sb(a.parent.id,a.name);a.Va=nb[b];return nb[b]=a}
var ub={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function vb(a,b){try{return hb(a,b),20}catch(c){}return 0}function wb(){var a=4096;for(var b=0;b<=a;b++)if(!lb[b])return b;throw new H(33);}function xb(a){yb||(yb=function(){},yb.prototype={});var b=new yb,c;for(c in a)b[c]=a[c];a=b;b=wb();a.fd=b;return lb[b]=a}var eb={open:function(a){a.U=kb[a.node.rdev].U;a.U.open&&a.U.open(a)},ma:function(){throw new H(70);}};function ab(a,b){kb[a]={U:b}}
function zb(a,b){var c="/"===b,d=!b;if(c&&jb)throw new H(10);if(!c&&!d){var e=J(b,{Ea:!1});b=e.path;e=e.node;if(e.sa)throw new H(10);if(16384!==(e.mode&61440))throw new H(54);}b={type:a,lb:{},Ha:b,Ua:[]};a=a.ea(b);a.ea=b;b.root=a;c?jb=a:e&&(e.sa=b,e.ea&&e.ea.Ua.push(b))}function Ab(a,b,c){var d=J(a,{parent:!0}).node;a=Wa(a);if(!a||"."===a||".."===a)throw new H(28);var e=vb(d,a);if(e)throw new H(e);if(!d.R.ra)throw new H(63);return d.R.ra(d,a,b,c)}function K(a){return Ab(a,16895,0)}
function Bb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Ab(a,b|8192,c)}function Cb(a,b){if(!Ya(a))throw new H(44);var c=J(b,{parent:!0}).node;if(!c)throw new H(44);b=Wa(b);var d=vb(c,b);if(d)throw new H(d);if(!c.R.symlink)throw new H(63);c.R.symlink(c,b,a)}function qb(a){a=J(a).node;if(!a)throw new H(44);if(!a.R.readlink)throw new H(28);return Ya(rb(a.parent),a.R.readlink(a))}
function Db(a,b,c){if(""===a)throw new H(44);if("string"===typeof b){var d=ub[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var e=a;else{a=Ua(a);try{e=J(a,{Da:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=Ab(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new H(54);if(!d){if(e)if(40960===(e.mode&61440))c=
32;else{if(c=16384===(e.mode&61440))c=["r","w","rw"][b&3],b&512&&(c+="w"),c="r"!==c||b&512;c=c?31:0}else c=44;if(c)throw new H(c);}if(b&512){c=e;c="string"===typeof c?J(c,{Da:!0}).node:c;if(!c.R.ba)throw new H(63);if(16384===(c.mode&61440))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);c.R.ba(c,{size:0,timestamp:Date.now()})}b&=-131713;e=xb({node:e,path:rb(e),flags:b,seekable:!0,position:0,U:e.U,mb:[],error:!1});e.U.open&&e.U.open(e);!g.logReadFiles||b&1||(Eb||(Eb={}),a in Eb||(Eb[a]=1,
y("FS.trackingDelegate error on read file: "+a)));try{pb.onOpenFile&&(c=0,1!==(b&2097155)&&(c|=1),0!==(b&2097155)&&(c|=2),pb.onOpenFile(a,c))}catch(f){y("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+f.message)}return e}function Fb(){H||(H=function(a,b){this.node=b;this.ab=function(c){this.ua=c};this.ab(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(function(a){gb[a]=new H(a);gb[a].stack="<generic error, no stack>"}))}var Gb;
function Hb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Ib(a,b,c){a=Ua("/dev/"+a);var d=Hb(!!b,!!c);Jb||(Jb=64);var e=Jb++<<8|0;ab(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,k,h,m){for(var l=0,p=0;p<m;p++){try{var q=b()}catch(r){throw new H(29);}if(void 0===q&&0===l)throw new H(6);if(null===q||void 0===q)break;l++;k[h+p]=q}l&&(f.node.timestamp=Date.now());return l},write:function(f,k,h,m){for(var l=0;l<m;l++)try{c(k[h+l])}catch(p){throw new H(29);}m&&(f.node.timestamp=Date.now());return l}});
Bb(a,d,e)}var Jb,Kb={},yb,Eb,Lb=void 0;function Mb(a){a=lb[a];if(!a)throw new H(8);return a}function Nb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ob=void 0;function L(a){for(var b="";A[a];)b+=Ob[A[a++]];return b}var M={},O={},Pb={};function Qb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Rb(a,b){a=Qb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Sb(a){var b=Error,c=Rb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var P=void 0;function Q(a){throw new P(a);}var Tb=void 0;function Ub(a){throw new Tb(a);}function R(a,b,c){function d(h){h=c(h);h.length!==a.length&&Ub("Mismatched type converter count");for(var m=0;m<a.length;++m)S(a[m],h[m])}a.forEach(function(h){Pb[h]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(h,m){O.hasOwnProperty(h)?e[m]=O[h]:(f.push(h),M.hasOwnProperty(h)||(M[h]=[]),M[h].push(function(){e[m]=O[h];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(O.hasOwnProperty(a)){if(c.Ra)return;Q("Cannot register type '"+d+"' twice")}O[a]=b;delete Pb[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(function(e){e()}))}function Vb(a){Q(a.O.W.T.name+" instance already deleted")}var Wb=!1;function Xb(){}
function Yb(a){--a.count.value;0===a.count.value&&(a.Y?a.Z.ha(a.Y):a.W.T.ha(a.S))}function Zb(a){if("undefined"===typeof FinalizationGroup)return Zb=function(b){return b},a;Wb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.S?Yb(c):console.warn("object already deleted: "+c.S)});Zb=function(b){Wb.register(b,b.O,b.O);return b};Xb=function(b){Wb.unregister(b.O)};return Zb(a)}var $b=void 0,ac=[];
function bc(){for(;ac.length;){var a=ac.pop();a.O.ja=!1;a["delete"]()}}function T(){}var cc={};function dc(a,b,c){if(void 0===a[b].X){var d=a[b];a[b]=function(){a[b].X.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].X+")!");return a[b].X[arguments.length].apply(this,arguments)};a[b].X=[];a[b].X[d.ia]=d}}
function ec(a,b){g.hasOwnProperty(a)?(Q("Cannot register public name '"+a+"' twice"),dc(g,a,a),g.hasOwnProperty(void 0)&&Q("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].X[void 0]=b):g[a]=b}function fc(a,b,c,d,e,f,k,h){this.name=a;this.constructor=b;this.ka=c;this.ha=d;this.$=e;this.Oa=f;this.oa=k;this.Na=h;this.Xa=[]}
function hc(a,b,c){for(;b!==c;)b.oa||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.oa(a),b=b.$;return a}function ic(a,b){if(null===b)return this.va&&Q("null is not a valid "+this.name),0;b.O||Q('Cannot pass "'+lc(b)+'" as a '+this.name);b.O.S||Q("Cannot pass deleted object as a pointer of type "+this.name);return hc(b.O.S,b.O.W.T,this.T)}
function mc(a,b){if(null===b){this.va&&Q("null is not a valid "+this.name);if(this.qa){var c=this.Ya();null!==a&&a.push(this.ha,c);return c}return 0}b.O||Q('Cannot pass "'+lc(b)+'" as a '+this.name);b.O.S||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.pa&&b.O.W.pa&&Q("Cannot convert argument of type "+(b.O.Z?b.O.Z.name:b.O.W.name)+" to parameter type "+this.name);c=hc(b.O.S,b.O.W.T,this.T);if(this.qa)switch(void 0===b.O.Y&&Q("Passing raw pointer to smart pointer is illegal"),
this.hb){case 0:b.O.Z===this?c=b.O.Y:Q("Cannot convert argument of type "+(b.O.Z?b.O.Z.name:b.O.W.name)+" to parameter type "+this.name);break;case 1:c=b.O.Y;break;case 2:if(b.O.Z===this)c=b.O.Y;else{var d=b.clone();c=this.Za(c,U(function(){d["delete"]()}));null!==a&&a.push(this.ha,c)}break;default:Q("Unsupporting sharing policy")}return c}
function nc(a,b){if(null===b)return this.va&&Q("null is not a valid "+this.name),0;b.O||Q('Cannot pass "'+lc(b)+'" as a '+this.name);b.O.S||Q("Cannot pass deleted object as a pointer of type "+this.name);b.O.W.pa&&Q("Cannot convert argument of type "+b.O.W.name+" to parameter type "+this.name);return hc(b.O.S,b.O.W.T,this.T)}function oc(a){return this.fromWireType(E[a>>2])}function pc(a,b,c){if(b===c)return a;if(void 0===c.$)return null;a=pc(a,b,c.$);return null===a?null:c.Na(a)}var qc={};
function rc(a,b){for(void 0===b&&Q("ptr should not be undefined");a.$;)b=a.oa(b),a=a.$;return qc[b]}function sc(a,b){b.W&&b.S||Ub("makeClassHandle requires ptr and ptrType");!!b.Z!==!!b.Y&&Ub("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Zb(Object.create(a,{O:{value:b}}))}
function W(a,b,c,d){this.name=a;this.T=b;this.va=c;this.pa=d;this.qa=!1;this.ha=this.Za=this.Ya=this.Ja=this.hb=this.Wa=void 0;void 0!==b.$?this.toWireType=mc:(this.toWireType=d?ic:nc,this.da=null)}function tc(a,b){g.hasOwnProperty(a)||Ub("Replacing nonexistant public symbol");g[a]=b;g[a].ia=void 0}
function uc(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=Fa.get(b).apply(null,c);return d}}function X(a,b){a=L(a);var c=a.includes("j")?uc(a,b):Fa.get(b);"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var vc=void 0;function wc(a){a=xc(a);var b=L(a);Y(a);return b}
function yc(a,b){function c(f){e[f]||O[f]||(Pb[f]?Pb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new vc(a+": "+d.map(wc).join([", "]));}function zc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Rb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function Ac(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Bc(a,b,c,d,e){var f=b.length;2>f&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,h=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].da){h=!0;break}var m="void"!==b[0].name,l="",p="";for(c=0;c<f-2;++c)l+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Qb(a)+"("+l+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";h&&(a+="var destructors = [];\n");var q=h?"destructors":"null";l="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Q,d,e,Ac,b[0],b[1]];k&&(a+="var thisWired = classParam.toWireType("+q+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+q+", arg"+c+"); // "+b[c+2].name+"\n",l.push("argType"+c),d.push(b[c+2]);k&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(h)a+=
"runDestructors(destructors);\n";else for(c=k?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].da&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",l.push(f+"_dtor"),d.push(b[c].da));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");l.push(a+"}\n");return zc(l).apply(null,d)}function Cc(a,b){for(var c=[],d=0;d<a;d++)c.push(C[(b>>2)+d]);return c}var Dc=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ec(a){4<a&&0===--Z[a].ya&&(Z[a]=void 0,Dc.push(a))}
function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Dc.length?Dc.pop():Z.length;Z[b]={ya:1,value:a};return b}}function lc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Fc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Da[c>>2])};case 3:return function(c){return this.fromWireType(Ea[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Gc(a,b,c){switch(b){case 0:return c?function(d){return D[d]}:function(d){return A[d]};case 1:return c?function(d){return B[d>>1]}:function(d){return wa[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return E[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Hc(a){a||Q("Cannot use deleted val. handle = "+a);return Z[a].value}function Ic(a,b){var c=O[a];void 0===c&&Q(b+" has unknown type "+wc(a));return c}var Jc={};
function Kc(a){var b=Jc[a];return void 0===b?L(a):b}var Lc=[];function Mc(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Nc(a){var b=Lc.length;Lc.push(a);return b}function Oc(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Ic(C[(b>>2)+d],"parameter "+d);return c}var Pc={};function tb(a,b,c,d){a||(a=this);this.parent=a;this.ea=a.ea;this.sa=null;this.id=mb++;this.name=b;this.mode=c;this.R={};this.U={};this.rdev=d}
Object.defineProperties(tb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Fb();nb=Array(4096);zb(I,"/");K("/tmp");K("/home");K("/home/web_user");
(function(){K("/dev");ab(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Bb("/dev/null",259);$a(1280,cb);$a(1536,db);Bb("/dev/tty",1280);Bb("/dev/tty1",1536);var a=Xa();Ib("random",a);Ib("urandom",a);K("/dev/shm");K("/dev/shm/tmp")})();
(function(){K("/proc");var a=K("/proc/self");K("/proc/self/fd");zb({ea:function(){var b=fb(a,"fd",16895,73);b.R={lookup:function(c,d){var e=lb[+d];if(!e)throw new H(8);c={parent:null,ea:{Ha:"fake"},R:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var Qc=Array(256),Rc=0;256>Rc;++Rc)Qc[Rc]=String.fromCharCode(Rc);Ob=Qc;P=g.BindingError=Sb("BindingError");Tb=g.InternalError=Sb("InternalError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.O.W.T,c=this.O.S,d=a.O.W.T;for(a=a.O.S;b.$;)c=b.oa(c),b=b.$;for(;d.$;)a=d.oa(a),d=d.$;return b===d&&c===a};T.prototype.clone=function(){this.O.S||Vb(this);if(this.O.na)return this.O.count.value+=1,this;var a=Zb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.O;a=a(c.call(b,d,{O:{value:{count:e.count,ja:e.ja,na:e.na,S:e.S,W:e.W,Y:e.Y,Z:e.Z}}}));a.O.count.value+=1;a.O.ja=!1;return a};
T.prototype["delete"]=function(){this.O.S||Vb(this);this.O.ja&&!this.O.na&&Q("Object already scheduled for deletion");Xb(this);Yb(this.O);this.O.na||(this.O.Y=void 0,this.O.S=void 0)};T.prototype.isDeleted=function(){return!this.O.S};T.prototype.deleteLater=function(){this.O.S||Vb(this);this.O.ja&&!this.O.na&&Q("Object already scheduled for deletion");ac.push(this);1===ac.length&&$b&&$b(bc);this.O.ja=!0;return this};W.prototype.Pa=function(a){this.Ja&&(a=this.Ja(a));return a};
W.prototype.Ba=function(a){this.ha&&this.ha(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=oc;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.qa?sc(this.T.ka,{W:this.Wa,S:c,Z:this,Y:a}):sc(this.T.ka,{W:this,S:a})}var c=this.Pa(a);if(!c)return this.Ba(a),null;var d=rc(this.T,c);if(void 0!==d){if(0===d.O.count.value)return d.O.S=c,d.O.Y=a,d.clone();d=d.clone();this.Ba(a);return d}d=this.T.Oa(c);d=cc[d];if(!d)return b.call(this);d=this.pa?d.Ma:d.pointerType;var e=pc(c,this.T,d.T);return null===e?b.call(this):this.qa?sc(d.T.ka,{W:d,S:e,Z:this,Y:a}):sc(d.T.ka,{W:d,S:e})};
g.getInheritedInstanceCount=function(){return Object.keys(qc).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in qc)qc.hasOwnProperty(b)&&a.push(qc[b]);return a};g.flushPendingDeletes=bc;g.setDelayFunction=function(a){$b=a;ac.length&&$b&&$b(bc)};vc=g.UnboundTypeError=Sb("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Sc={d:function(a){return ib(a+16)+16},e:function(a,b,c){(new Ra(a)).Sa(b,c);Sa++;throw a;},A:function(a,b,c){Lb=c;try{var d=a?z(A,a,void 0):"";if(c){Lb+=4;var e=C[Lb-4>>2]}else e=0;return Db(d,b,e).fd}catch(f){return"undefined"!==typeof Kb&&f instanceof H||x(f),-f.ua}},v:function(){},C:function(a,b,c,d,e){var f=Nb(c);b=L(b);S(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=D;else if(2===c)h=B;
else if(4===c)h=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>f])},da:null})},l:function(a,b,c,d,e,f,k,h,m,l,p,q,r){p=L(p);f=X(e,f);h&&(h=X(k,h));l&&(l=X(m,l));r=X(q,r);var w=Qb(p);ec(w,function(){yc("Cannot construct "+p+" due to unbound types",[d])});R([a,b,c],d?[d]:[],function(v){v=v[0];if(d){var V=v.T;var N=V.ka}else N=T.prototype;v=Rb(w,function(){if(Object.getPrototypeOf(this)!==ob)throw new P("Use 'new' to construct "+p);if(void 0===da.ga)throw new P(p+
" has no accessible constructor");var jc=da.ga[arguments.length];if(void 0===jc)throw new P("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(da.ga).toString()+") parameters instead!");return jc.apply(this,arguments)});var ob=Object.create(N,{constructor:{value:v}});v.prototype=ob;var da=new fc(p,v,ob,r,V,f,h,l);V=new W(p,da,!0,!1);N=new W(p+"*",da,!1,!1);var kc=new W(p+" const*",da,!1,!0);cc[a]={pointerType:N,Ma:kc};tc(w,v);return[V,
N,kc]})},b:function(a,b,c,d,e,f,k){var h=Cc(c,d);b=L(b);f=X(e,f);R([],[a],function(m){function l(){yc("Cannot call "+p+" due to unbound types",h)}m=m[0];var p=m.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var q=m.T.constructor;void 0===q[b]?(l.ia=c-1,q[b]=l):(dc(q,b,p),q[b].X[c-1]=l);R([],h,function(r){r=[r[0],null].concat(r.slice(1));r=Bc(p,r,null,f,k);void 0===q[b].X?(r.ia=c-1,q[b]=r):q[b].X[c-1]=r;return[]});return[]})},p:function(a,b,c,d,e,f,k,h){b=L(b);f=X(e,f);R([],[a],function(m){m=
m[0];var l=m.name+"."+b,p={get:function(){yc("Cannot access "+l+" due to unbound types",[c])},enumerable:!0,configurable:!0};h?p.set=function(){yc("Cannot access "+l+" due to unbound types",[c])}:p.set=function(){Q(l+" is a read-only property")};Object.defineProperty(m.T.constructor,b,p);R([],[c],function(q){q=q[0];var r={get:function(){return q.fromWireType(f(d))},enumerable:!0};h&&(h=X(k,h),r.set=function(w){var v=[];h(d,q.toWireType(v,w));Ac(v)});Object.defineProperty(m.T.constructor,b,r);return[]});
return[]})},q:function(a,b,c,d,e,f){assert(0<b);var k=Cc(b,c);e=X(d,e);var h=[f],m=[];R([],[a],function(l){l=l[0];var p="constructor "+l.name;void 0===l.T.ga&&(l.T.ga=[]);if(void 0!==l.T.ga[b-1])throw new P("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.T.ga[b-1]=function(){yc("Cannot construct "+l.name+" due to unbound types",k)};R([],
k,function(q){l.T.ga[b-1]=function(){arguments.length!==b-1&&Q(p+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;h.length=b;for(var r=1;r<b;++r)h[r]=q[r].toWireType(m,arguments[r-1]);r=e.apply(null,h);Ac(m);return q[0].fromWireType(r)};return[]});return[]})},f:function(a,b,c,d,e,f,k,h){var m=Cc(c,d);b=L(b);f=X(e,f);R([],[a],function(l){function p(){yc("Cannot call "+q+" due to unbound types",m)}l=l[0];var q=l.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&
l.T.Xa.push(b);var r=l.T.ka,w=r[b];void 0===w||void 0===w.X&&w.className!==l.name&&w.ia===c-2?(p.ia=c-2,p.className=l.name,r[b]=p):(dc(r,b,q),r[b].X[c-2]=p);R([],m,function(v){v=Bc(q,v,l,f,k);void 0===r[b].X?(v.ia=c-2,r[b]=v):r[b].X[c-2]=v;return[]});return[]})},B:function(a,b){b=L(b);S(a,{name:b,fromWireType:function(c){var d=Z[c].value;Ec(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:oc,da:null})},r:function(a,b,c){c=Nb(c);b=L(b);S(a,{name:b,fromWireType:function(d){return d},
toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+lc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Fc(b,c),da:null})},k:function(a,b,c,d,e){function f(l){return l}b=L(b);-1===e&&(e=4294967295);var k=Nb(c);if(0===d){var h=32-8*c;f=function(l){return l<<h>>>h}}var m=b.includes("unsigned");S(a,{name:b,fromWireType:f,toWireType:function(l,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+
lc(p)+'" to '+this.name);if(p<d||p>e)throw new TypeError('Passing a number "'+lc(p)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:Gc(b,k,0!==d),da:null})},g:function(a,b,c){function d(f){f>>=2;var k=E;return new e(Ca,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=L(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,
readValueFromPointer:d},{Ra:!0})},s:function(a,b){b=L(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var e=E[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var h=d+4+k;if(k==e||0==A[h]){f=f?z(A,f,h-f):"";if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=h+1}}else{m=Array(e);for(k=0;k<e;++k)m[k]=String.fromCharCode(A[d+4+k]);m=m.join("")}Y(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof
Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");var k=(c&&f?function(){return ta(e)}:function(){return e.length})(),h=ib(4+k+1);E[h>>2]=k;if(c&&f)sa(e,A,h+4,k+1);else if(f)for(f=0;f<k;++f){var m=e.charCodeAt(f);255<m&&(Y(h),Q("String has UTF-16 code units that do not fit in 8 bits"));A[h+4+f]=m}else for(f=0;f<k;++f)A[h+4+f]=e[f];null!==d&&d.push(Y,h);return h},argPackAdvance:8,readValueFromPointer:oc,da:function(d){Y(d)}})},o:function(a,b,c){c=L(c);if(2===b){var d=
va;var e=xa;var f=ya;var k=function(){return wa};var h=1}else 4===b&&(d=za,e=Aa,f=Ba,k=function(){return E},h=2);S(a,{name:c,fromWireType:function(m){for(var l=E[m>>2],p=k(),q,r=m+4,w=0;w<=l;++w){var v=m+4+w*b;if(w==l||0==p[v>>h])r=d(r,v-r),void 0===q?q=r:(q+=String.fromCharCode(0),q+=r),r=v+b}Y(m);return q},toWireType:function(m,l){"string"!==typeof l&&Q("Cannot pass non-string to C++ string type "+c);var p=f(l),q=ib(4+p+b);E[q>>2]=p>>h;e(l,q+4,p+b);null!==m&&m.push(Y,q);return q},argPackAdvance:8,
readValueFromPointer:oc,da:function(m){Y(m)}})},D:function(a,b){b=L(b);S(a,{Ta:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},i:function(a,b,c){a=Hc(a);b=Ic(b,"emval::as");var d=[],e=U(d);C[c>>2]=e;return b.toWireType(d,a)},E:function(a,b,c,d,e){a=Lc[a];b=Hc(b);c=Kc(c);var f=[];C[d>>2]=U(f);return a(b,c,f,e)},F:function(a,b,c,d){a=Lc[a];b=Hc(b);c=Kc(c);a(b,c,null,d)},a:Ec,u:function(a){if(0===a)return U(Mc());a=Kc(a);return U(Mc()[a])},t:function(a,b){b=Oc(a,b);for(var c=
b[0],d=c.name+"_$"+b.slice(1).map(function(l){return l.name}).join("_")+"$",e=["retType"],f=[c],k="",h=0;h<a-1;++h)k+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),f.push(b[1+h]);d="return function "+Qb("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(h=0;h<a-1;++h)d+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[h+1].argPackAdvance;d+="    var rv = handle[name]("+k+");\n";for(h=0;h<a-1;++h)b[h+1].deleteObject&&(d+="    argType"+h+".deleteObject(arg"+
h+");\n");c.Ta||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=zc(e).apply(null,f);return Nc(a)},j:function(a,b){a=Hc(a);b=Hc(b);return U(a[b])},c:function(a){4<a&&(Z[a].ya+=1)},G:function(a,b,c,d){a=Hc(a);var e=Pc[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)k+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+
f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",k+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Ic,g,U);Pc[b]=e}return e(a,c,d)},m:function(a){return U(Kc(a))},h:function(a){Ac(Z[a].value);Ec(a)},n:function(a,b){a=Ic(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},x:function(){x()},w:function(){x("OOM")},y:function(a){try{var b=
Mb(a);if(null===b.fd)throw new H(8);b.Qa&&(b.Qa=null);try{b.U.close&&b.U.close(b)}catch(c){throw c;}finally{lb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof Kb&&c instanceof H||x(c),c.ua}},z:function(a,b,c,d){try{a:{for(var e=Mb(a),f=a=0;f<c;f++){var k=C[b+(8*f+4)>>2],h=e,m=C[b+8*f>>2],l=k,p=void 0,q=D;if(0>l||0>p)throw new H(28);if(null===h.fd)throw new H(8);if(1===(h.flags&2097155))throw new H(8);if(16384===(h.node.mode&61440))throw new H(31);if(!h.U.read)throw new H(28);var r=
"undefined"!==typeof p;if(!r)p=h.position;else if(!h.seekable)throw new H(70);var w=h.U.read(h,q,m,l,p);r||(h.position+=w);var v=w;if(0>v){var V=-1;break a}a+=v;if(v<k)break}V=a}C[d>>2]=V;return 0}catch(N){return"undefined"!==typeof Kb&&N instanceof H||x(N),N.ua}}};
(function(){function a(e){g.asm=e.exports;pa=g.asm.H;Ca=e=pa.buffer;g.HEAP8=D=new Int8Array(e);g.HEAP16=B=new Int16Array(e);g.HEAP32=C=new Int32Array(e);g.HEAPU8=A=new Uint8Array(e);g.HEAPU16=wa=new Uint16Array(e);g.HEAPU32=E=new Uint32Array(e);g.HEAPF32=Da=new Float32Array(e);g.HEAPF64=Ea=new Float64Array(e);Fa=g.asm.K;Ha.unshift(g.asm.I);F--;g.monitorRunDependencies&&g.monitorRunDependencies(F);0==F&&(null!==Ka&&(clearInterval(Ka),Ka=null),La&&(e=La,La=null,e()))}function b(e){a(e.instance)}function c(e){return Pa().then(function(f){return WebAssembly.instantiate(f,
d)}).then(e,function(f){y("failed to asynchronously prepare wasm: "+f);x(f)})}var d={a:Sc};F++;g.monitorRunDependencies&&g.monitorRunDependencies(F);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return oa||"function"!==typeof WebAssembly.instantiateStreaming||Ma()||G.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(f){y("wasm streaming compile failed: "+f);y("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.I).apply(null,arguments)};var ib=g._malloc=function(){return(ib=g._malloc=g.asm.J).apply(null,arguments)},Y=g._free=function(){return(Y=g._free=g.asm.L).apply(null,arguments)},xc=g.___getTypeName=function(){return(xc=g.___getTypeName=g.asm.M).apply(null,arguments)};
g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.N).apply(null,arguments)};var Tc;La=function Uc(){Tc||Vc();Tc||(La=Uc)};
function Vc(){function a(){if(!Tc&&(Tc=!0,g.calledRun=!0,!qa)){g.noFSInit||Gb||(Gb=!0,Fb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Ib("stdin",g.stdin):Cb("/dev/tty","/dev/stdin"),g.stdout?Ib("stdout",null,g.stdout):Cb("/dev/tty","/dev/stdout"),g.stderr?Ib("stderr",null,g.stderr):Cb("/dev/tty1","/dev/stderr"),Db("/dev/stdin",0),Db("/dev/stdout",1),Db("/dev/stderr",1));Qa(Ha);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&
(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ia.unshift(b)}Qa(Ia)}}if(!(0<F)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ja();Qa(Ga);0<F||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=Vc;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Vc();


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
